name: notion_dart_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  dio: ^4.0.6
  path: ^1.8.2
